/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.39
 * Generated at: 2020-12-03 15:53:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.manager.game;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ManagerGameUpdatePage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/I:/work2/store/WebContent/WEB-INF/lib/javax.servlet.jsp.jstl-1.2.1.jar!/META-INF/c.tld", Long.valueOf(1323225978000L));
    _jspx_dependants.put("/WEB-INF/lib/javax.servlet.jsp.jstl-1.2.1.jar", Long.valueOf(1605833312000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("* {\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("\tpadding: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".indexcenterdiv {\r\n");
      out.write("\twidth: 80%;\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("\tmargin: 0 auto;\r\n");
      out.write("\tpadding: 128px 0px;\r\n");
      out.write("\tdisplay: table;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".settingp {\r\n");
      out.write("\tmargin-top: 20px;\r\n");
      out.write("}\r\n");
      out.write(".editTable tr td{\r\n");
      out.write("\tpadding:4px 0;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function fileCheck(file1){  \t  // 사이즈체크\r\n");
      out.write("\tvar pathpoint1 = file1.value.lastIndexOf('.');\r\n");
      out.write("\tvar filepoint1 = file1.value.substring(pathpoint1+1,file1.length);\r\n");
      out.write("\tvar filetype1=filepoint1.toLowerCase();\r\n");
      out.write("\r\n");
      out.write("    var maxSize  = 5 * 1024 * 1024    //5MB\r\n");
      out.write("    var fileSize1 = 0;\r\n");
      out.write("    var fileSize2 = 0;\r\n");
      out.write("// 브라우저 확인\r\n");
      out.write("var browser=navigator.appName;\r\n");
      out.write("// 익스플로러일 경우\r\n");
      out.write("if (browser==\"Microsoft Internet Explorer\")\r\n");
      out.write("{\t\r\n");
      out.write("\tvar oas = new ActiveXObject(\"Scripting.FileSystemObject\");\r\n");
      out.write("\tif(file1!=null){\r\n");
      out.write("\tfileSize1 = oas.getFile( file1.value ).size;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("// 익스플로러가 아닐경우\r\n");
      out.write("else\r\n");
      out.write("{\t\r\n");
      out.write("\tif(file1.value!=''){\r\n");
      out.write("\t\tfileSize1 = file1.files[0].size;\r\n");
      out.write("\t\tif(filetype1=='jpg'||filetype1=='gif'||filetype1=='png'||filetype1=='jpeg'||filetype1=='bmp')\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\talert(\"이미지 파일만 첨부 가능합니다.\");\r\n");
      out.write("\t        return;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t    if(fileSize1 > maxSize)\r\n");
      out.write("\t    {\r\n");
      out.write("\t        alert(\"첨부파일 사이즈는 5MB 이내로 등록 가능합니다.\");\r\n");
      out.write("\t        return;\r\n");
      out.write("\t    }\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("//값이 비어있는지 체크\r\n");
      out.write("var gameTitle  = document.getElementById(\"gameTitle\");\r\n");
      out.write("var gameContent1 = document.getElementById(\"gameContent1\");\r\n");
      out.write("var gameContent2 = document.getElementById(\"gameContent2\");\r\n");
      out.write("var keyart = document.getElementById(\"keyart\");\r\n");
      out.write("var price1 = document.getElementById(\"price1\");\r\n");
      out.write("var price2 = document.getElementById(\"price2\");\r\n");
      out.write("var gameTag1 = document.getElementById(\"gameTag1\");\r\n");
      out.write("var gameTag2 = document.getElementById(\"gameTag2\");\r\n");
      out.write("var gameTag3 = document.getElementById(\"gameTag3\");\r\n");
      out.write("var gameTag4 = document.getElementById(\"gameTag4\");\r\n");
      out.write("var specialofferyn = document.getElementById(\"specialofferyn\");\r\n");
      out.write("var freegameyn = document.getElementById(\"freegameyn\");\r\n");
      out.write("var newgameyn = document.getElementById(\"newgameyn\");\r\n");
      out.write("var useyn = document.getElementById(\"useyn\");\r\n");
      out.write("\r\n");
      out.write("if(keyart.value.length>100){\r\n");
      out.write("\talert(\"파일 이름이 너무 길어요.. 최대 100자\");\r\n");
      out.write("\treturn;\r\n");
      out.write("}\r\n");
      out.write("if(gameTitle.value==''||gameTitle.value==null){\r\n");
      out.write("\talert(\"게임 제목을 입력해 주세요!\");\r\n");
      out.write("\treturn;\r\n");
      out.write("}else if(gameContent1.value==\"\"||gameContent1.value==null){\r\n");
      out.write("\talert(\"게임 내용1를 입력해 주세요!\");\r\n");
      out.write("\treturn\r\n");
      out.write("}else if(gameContent2.value==\"\"||gameContent2.value==null){\r\n");
      out.write("\talert(\"게임 내용2를 입력해 주세요!\");\r\n");
      out.write("\treturn\r\n");
      out.write("}else if(price1.value==\"\"||price1.value==null){\r\n");
      out.write("\talert(\"가격1를 입력해 주세요!\");\r\n");
      out.write("\treturn\r\n");
      out.write("}else if(price1.value<0||price1.value>90000){\r\n");
      out.write("\talert(\"가격1: 0원이상 9만원 이하\");\r\n");
      out.write("\treturn\r\n");
      out.write("}else if(price2.value<0||price2.value==null){\r\n");
      out.write("\talert(\"가격2를 입력해 주세요!\");\r\n");
      out.write("\treturn\r\n");
      out.write("}else if(price2.value<0||price2.value>80000){\r\n");
      out.write("\talert(\"가격2: 0원이상 8만원 이하\");\r\n");
      out.write("\treturn\r\n");
      out.write("}else if(parseInt(price1.value,10)<parseInt(price2.value,10)){\r\n");
      out.write("\talert(\"가격1이 더 높게 설정해주세요...\");\r\n");
      out.write("\treturn\r\n");
      out.write("}else if(gameTag1.value==\"\"||gameTag1.value==null){\r\n");
      out.write("\talert(\"게임 태그1를 입력해 주세요!\");\r\n");
      out.write("\treturn\r\n");
      out.write("}else if(gameTag2.value==\"\"||gameTag2.value==null){\r\n");
      out.write("\talert(\"게임 태그2를 입력해 주세요!\");\r\n");
      out.write("\treturn\r\n");
      out.write("}else if(specialofferyn.value==\"\"||specialofferyn.value==null){\r\n");
      out.write("\talert(\"특별할인 여부를 입력해 주세요!\");\r\n");
      out.write("\treturn\r\n");
      out.write("}else if(freegameyn.value==\"\"||freegameyn.value==null){\r\n");
      out.write("\talert(\"무료게임 여부를 입력해 주세요!\");\r\n");
      out.write("\treturn\r\n");
      out.write("}else if(newgameyn.value==\"\"|newgameyn.value==null){\r\n");
      out.write("\talert(\"신작 게임 여부를 입력해 주세요!\");\r\n");
      out.write("\treturn\r\n");
      out.write("}else if(useyn.value==\"\"|useyn.value==null){\r\n");
      out.write("\talert(\"게임 숨김 여부를 입력해 주세요!\");\r\n");
      out.write("\treturn\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("document.updatefileForm.submit();\r\n");
      out.write("}\r\n");
      out.write("function select(){\r\n");
      out.write("\tdocument.getElementById(\"useyn\").value=\"\"\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<form name=\"updatefileForm\" action=\"updateGame.go\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("\t\t<div class=\"center\" style=\"min-height: 600px\">\r\n");
      out.write("\t\t\t<div class=\"centermiddle\"\r\n");
      out.write("\t\t\t\tstyle=\"padding: 80px; width: 80%; height: 100%; margin: 0 auto;\">\r\n");
      out.write("\t\t\t\t<h1>게임 수정</h1>\r\n");
      out.write("\t\t\t\t<hr style=\"margin: 10px auto;\">\r\n");
      out.write("\t\t\t\t<p>신중하게 수정 부탁 드립니다.</p>\r\n");
      out.write("\t\t\t\t<!-- hidden -->\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"gseq\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${gameInfo.gseq}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<table class=\"editTable\" style=\"padding: 10px; margin: 0 auto; margin-top: 20px; width: 100%; height: 100%; background-color: #c2c2c2; border-radius: 6px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td style=\"width:10%;\">제목</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" id=\"gameTitle\" style=\"width: 100%; padding: 2px 0;\" name=\"subject\" placeholder=\"제목을 작성해주세요\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvalue=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${gameInfo.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" required />\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td style=\"width:10%;\">키아트 이미지</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"originalimage\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${gameInfo.keyart}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"file\" name=\"keyart\" id=\"keyart\"maxlength=\"150\" accept=\".gif, .jpg, .png\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td style=\"padding-top: 10px;\">내용1</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"100%\" style=\"\"><textarea id=\"gameContent1\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\trows=\"6\" style=\"width: 100%; resize: none;\" name=\"content1\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tplaceholder=\"이곳에 내용을 적어주세요!\" maxlength=\"330\" required>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${gameInfo.content1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td style=\"padding-top: 10px;\">내용2</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"100%\" style=\"\"><textarea id=\"gameContent2\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\trows=\"15\" style=\"width: 100%; resize: none;\" name=\"content2\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tplaceholder=\"이곳에 내용을 적어주세요!\" maxlength=\"2500\" required>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${gameInfo.content2}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td style=\"padding-top: 10px;\">가격1</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"number\" id=\"price1\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"price1\" min=\"10000\" max=\"90000\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${gameInfo.price1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/> 가격2(할인) <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttype=\"number\" id=\"price2\" name=\"price2\" min=\"10000\" max=\"80000\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${gameInfo.price2}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td style=\"padding-top: 10px;\">게임 태그</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"100%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<select name=\"tag1\" id=\"gameTag1\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\trequired>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"\">태그1</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"CO-OP\">CO-OP</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"싱글플레이\">싱글 플레이</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"멀티플레이\">멀티</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"싱글과 멀티플레이\">싱글과 멀티</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</select> <select name=\"tag2\" id=\"gameTag2\" required>\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"\">태그3</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"캐주얼\">캐주얼</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"아케이드\">아케이드</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"어드벤쳐\">어드벤쳐</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"액션\">액션</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</select> <select name=\"tag3\" id=\"gameTag3\" required>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"\">태그2</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"인디\">인디</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"오픈월드\">오픈월드</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"VR\">VR</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"전략\">전략</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"시뮬레이션 \">시뮬레이션</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"레이싱\">레이싱</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"스포츠\">스포츠</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"턴제\">턴제</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</select> <select name=\"tag4\" id=\"gameTag4\" required>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"\">태그4</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"일인칭\">일인칭 시점</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"삼인칭\">삼인칭 시점</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td style=\"padding-top: 10px;\">게임 상태</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"100%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<select name=\"adgameyn\" id=\"adgameyn\"required>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"n\">광고게임 여부</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"y\">Y</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"n\">N</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t<select name=\"specialofferyn\" id=\"specialofferyn\" required>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"\">특별할인 여부</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"y\">Y</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"n\">N</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t<select name=\"newgameyn\" id=\"newgameyn\"required>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"\">신작게임 여부</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"y\">Y</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"n\">N</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t<select name=\"freegameyn\" id=\"freegameyn\"required>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"\">무료게임 여부</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"y\">Y</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"n\">N</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td style=\"padding-top: 10px;\">숨김 처리</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"100%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<select name=\"useyn\" id=\"useyn\"required>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"\">숨김 여부</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"y\">Y-노출</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"n\">N-숨김</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"button\" onclick=\"select()\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t<input type=\"button\"\r\n");
      out.write("\t\t\t\t\tstyle=\"float: right; margin-top: 20px; padding: 5px 20px;\"\r\n");
      out.write("\t\t\t\t\tvalue=\"제 출\"\r\n");
      out.write("\t\t\t\t\tonclick=\"fileCheck( this.form.keyart )\" />\r\n");
      out.write("\t\t\t\t<input type=\"button\"\r\n");
      out.write("\t\t\t\t\tstyle=\"float: left; margin-top: 20px; padding: 5px 20px;\"\r\n");
      out.write("\t\t\t\t\tvalue=\"목 록\" onclick=\"location.href='javascript: history.back()'\" />\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
