/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.39
 * Generated at: 2020-12-01 02:44:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class test_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function rand(){\r\n");
      out.write("\t var result = Math.floor(Math.random() * 20)+1\r\n");
      out.write("\tdocument.frm.Q2.value = result;\r\n");
      out.write("}\r\n");
      out.write("function sorrt(){\r\n");
      out.write("var number=[1,15,8,69,45,23,37,19]\r\n");
      out.write("alert(number.sort(function (a,b){ return a-b; }));\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("function dandn(){\r\n");
      out.write("\tvar n = document.frm.dannumb.value;\r\n");
      out.write("\tif(n==0){\r\n");
      out.write("\t\talert(\"원하는 단을 입력해주세요..\");\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\t\tdocument.write(\"----------\"+n+\"단-----------\"+\"<br>\");\r\n");
      out.write("\t\tfor(var i=1; i<=9; i++){\r\n");
      out.write("\t\t\tdocument.write(n+\"*\"+i+\"=\"+n*i+\"<br>\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("function change04(){\r\n");
      out.write("\tvar target = document.getElementById(\"d04\");\r\n");
      out.write("\ttarget.style.background=\"red\";\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function changeBold(){\r\n");
      out.write("\tvar target2 = document.getElementById(\"d05\");\r\n");
      out.write("\ttarget2.style.fontWeight=\"bold\";\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function unCheck(){\r\n");
      out.write("\tvar chkbox = document.getElementsByName(\"chk\");\r\n");
      out.write("\tfor(var i=0; i<chkbox.length;i++){\r\n");
      out.write("\t\tif(chkbox[i].checked){\r\n");
      out.write("\t\t\tchkbox[i].checked=false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("function changeText(){\r\n");
      out.write("\tvar input = document.getElementById(\"readText\");\r\n");
      out.write("\tinput.style.color=\"red\";\r\n");
      out.write("\tinput.readOnly=true;\r\n");
      out.write("}\r\n");
      out.write("function disBtn(){\r\n");
      out.write("\tvar Btn = document.getElementById(\"thisBtn\");\r\n");
      out.write("\tBtn.disabled = true;\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("div{\r\n");
      out.write("padding:10px;\r\n");
      out.write("background:#c2c2c2;\r\n");
      out.write("display:table;\r\n");
      out.write("border-radius:6px;\r\n");
      out.write("}\r\n");
      out.write(".d{\r\n");
      out.write("background:yellow;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<form name=\"frm\">\r\n");
      out.write("<h2>문제 1</h2>\r\n");
      out.write("원하는 사이트 선택\r\n");
      out.write("<div>\r\n");
      out.write("<input type=\"radio\" value=\"네이버\" onclick=\"window.open('http://www.naver.com')\"/>네이버<br>\r\n");
      out.write("<input type=\"radio\" value=\"다음\" onclick=\"window.open('http://www.daum.net')\"/>다음<br>\r\n");
      out.write("<input type=\"radio\" value=\"유튜브\" onclick=\"window.open('http://www.youtube.com')\"/>유튜브<br>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<h2>문제 2</h2>\r\n");
      out.write("1~20숫자 랜덤 생성\r\n");
      out.write("<div>\r\n");
      out.write("출력:<input type=\"text\" name=\"Q2\" value=\"1-20랜덤생성\"/><input type=\"button\" value=\"생성\" onclick=\"rand()\"/>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<h2>문제 3</h2>\r\n");
      out.write("이동할 페이지를 선택하세요\r\n");
      out.write("<div>\r\n");
      out.write("<select name=\"jump\" onchange=\"location.href=this.value\">\r\n");
      out.write("<option>선택</option>\r\n");
      out.write("<option value=\"http://www.naver.com\">네이버</option>\r\n");
      out.write("<option value=\"http://www.daum.net\">다음</option>\r\n");
      out.write("</select>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<h2>문제 4</h2>\r\n");
      out.write("보기의 숫자를 정렬 해 주세요.\r\n");
      out.write("<div>\r\n");
      out.write("<p>*숫자:1,15,8,69,45,23,37,19</p>\r\n");
      out.write("<p>*정렬:</p>\r\n");
      out.write("<input type=\"button\" value=\"숫자정렬\" onclick=\"sorrt()\"/>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<h2>문제 5</h2>\r\n");
      out.write("원하는 구구단을 입력하고 결과 출력\r\n");
      out.write("<div>\r\n");
      out.write("<input type=\"text\" name=\"dannumb\"/><input type=\"button\" value=\"구구단출력\" onclick=\"dandn()\"/>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<h2>문제 6</h2>\r\n");
      out.write("버튼은 disabled시키기\r\n");
      out.write("<div>\r\n");
      out.write("<input type=\"button\" value=\"아래 버튼 disabled 시키기\" onclick=\"disBtn()\"/><br><br>\r\n");
      out.write("<input type=\"button\" value=\"난 버튼이야\" id=\"thisBtn\" onclick=\"sorrt()\"/>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<h2>문제 7</h2>\r\n");
      out.write("두 번째 타겟04의 배경색 변경\r\n");
      out.write("<input type=\"button\" value=\"타겟04\" onclick=\"change04()\"/>\r\n");
      out.write("<div style=\"width:200px; height:100px;\">\r\n");
      out.write("\t<div class=\"d\">target.04      </div>\r\n");
      out.write("\t<div class=\"d\" id=\"d04\">target.04        </div>\r\n");
      out.write("\t<div class=\"d\">target.04      </div>\r\n");
      out.write("\t<div class=\"d\">target.04      </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<h2>문제 8</h2>\r\n");
      out.write("bold라고 적힌 엘리먼트의 bold효과 적용\r\n");
      out.write("<input type=\"button\" value=\"타겟bold\" onclick=\"changeBold()\"/>\r\n");
      out.write("<div style=\"width:200px; height:100px;\">\r\n");
      out.write("\t<div class=\"d\"  id=\"d05\">bold</div>\r\n");
      out.write("\t<div class=\"d\">blink</div>\r\n");
      out.write("\t<div class=\"d\">strike</div>\r\n");
      out.write("</div>\r\n");
      out.write("<h2>문제 9</h2>\r\n");
      out.write("읽기만 가능하게 하고 폰트색깔 red\r\n");
      out.write("<div>\r\n");
      out.write("<input type=\"button\" value=\"타겟Red\" onclick=\"changeText()\"/><br>\r\n");
      out.write("<input type=\"text\" value=\"읽기만 가능하게 하시오\" id=\"readText\" />\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<h2>문제 10</h2>\r\n");
      out.write("모든 체크박스 해제\r\n");
      out.write("<div>\r\n");
      out.write("<input type=\"button\" value=\"언체크\" onclick=\"unCheck()\"/><br>\r\n");
      out.write("<input type=\"checkbox\" name=\"chk\" value=\"uncheck!\" checked/>uncheck!<br>\r\n");
      out.write("<input type=\"checkbox\" name=\"chk\" value=\"uncheck!\" checked/>uncheck!<br>\r\n");
      out.write("<input type=\"checkbox\" name=\"chk\" value=\"uncheck!\" checked/>uncheck!<br>\r\n");
      out.write("<input type=\"checkbox\" name=\"chk\" value=\"uncheck!\" checked/>uncheck!<br>\r\n");
      out.write("</div>\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
