/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.39
 * Generated at: 2020-10-21 08:16:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.market.img;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class loginPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>냠냠 마켓 로그인 페이지</title>\r\n");
      out.write("<style>\r\n");
      out.write(".top {\r\n");
      out.write(" \tmargin: 0px auto;\r\n");
      out.write("\theight: 54px;\r\n");
      out.write("}\r\n");
      out.write(".top>p>img {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\theight: 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".center {\r\n");
      out.write("\theight: 400px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".centerbox {\r\n");
      out.write("\twidth: 400px;\r\n");
      out.write("\theight: 300px;\r\n");
      out.write("\tborder: 1px solid #d9d9d9;\r\n");
      out.write("\tmargin: 0 auto;\r\n");
      out.write("\tborder-radius: 8px;\r\n");
      out.write("}\r\n");
      out.write(".loginbox1 {\r\n");
      out.write("\twidth: 340px;\r\n");
      out.write("\theight: 160px;\r\n");
      out.write("\tmargin: 20px auto;\r\n");
      out.write("\tfont-size:16px;\r\n");
      out.write("\tfont-family:Arial;\r\n");
      out.write("\tfont-weight: normal;\r\n");
      out.write("}\r\n");
      out.write(".loginbox1 input{\r\n");
      out.write("\twidth: 280px;\r\n");
      out.write("\theight: 30px;\r\n");
      out.write("\tmargin-left:10px;\r\n");
      out.write("\tborder: 1px solid #7a7a7a;\r\n");
      out.write("\tborder-radius: 3px;\r\n");
      out.write("}\r\n");
      out.write(".loginbox2{\r\n");
      out.write("\tmargin: 0 auto;\r\n");
      out.write("\twidth:340px;\r\n");
      out.write("\theight:92px;\r\n");
      out.write("}\r\n");
      out.write(".loginbox2>p{\r\n");
      out.write("\tfont-size: 14px;\r\n");
      out.write("\tmargin:20px auto;\r\n");
      out.write("}\r\n");
      out.write("\t\r\n");
      out.write(".loginbox2>p>input{\r\n");
      out.write("\twidth:340px; height:34px; \r\n");
      out.write("\tbackground-color:#ffea00;\r\n");
      out.write("\tborder: 1px solid #a68200;\r\n");
      out.write("\tborder-radius: 3px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".loginbox3{\r\n");
      out.write("\tmargin:30px auto;\r\n");
      out.write("\twidth:340px;\r\n");
      out.write("\theight:98px;\r\n");
      out.write("}\r\n");
      out.write(".loginbox3>p{\r\n");
      out.write("\tfont-family: arial;\r\n");
      out.write("\tfont-size: 14px;\r\n");
      out.write("\tcolor: gray;\r\n");
      out.write("\tmargin:10px auto;\r\n");
      out.write("}\r\n");
      out.write(".loginbox3>p>input{\r\n");
      out.write("\twidth:340px; height:34px;\r\n");
      out.write("\tborder:1px solid gray;\r\n");
      out.write("\tborder-radius:3px;\r\n");
      out.write("}\r\n");
      out.write("a:link{\r\n");
      out.write("\tcolor: #16528a;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("}\r\n");
      out.write(" a:visited{\r\n");
      out.write("\tcolor: #16528a;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("}\r\n");
      out.write(".bottom>p{\r\n");
      out.write("\tcolor: gray;\r\n");
      out.write("\tfont-family:arial;\r\n");
      out.write("\tfont-size:14px;\r\n");
      out.write("\tletter-spacing:1px;\r\n");
      out.write("}\r\n");
      out.write(";\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<form action=\"/webapp/ServletEx8\" method=\"post\">\r\n");
      out.write("\t\t<div class=\"top\">\r\n");
      out.write("\t\t\t<p align=\"center\"><img src=\"img/nyamlogo.png\"/></p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"center\">\r\n");
      out.write("\t\t\t<div class=\"centerbox\">\r\n");
      out.write("\t\t\t\t<table class=\"loginbox1\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"2\" style=\"font-size:26px; font-weight:bold;\">Sign-In</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t<td><p>MAIL<p></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"mail\"/></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t<td><p>PW<p></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"password\" name=\"pw\"/></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t<div class=\"loginbox2\">\r\n");
      out.write("\t\t\t\t\t<p><input type=\"submit\" name=\"submit\" value=\"로그인\"/><p>\r\n");
      out.write("\t\t\t\t\t<p><a href=\"https://www.naver.com\">▶ 도움이 필요하세요?</a></p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"loginbox3\">\r\n");
      out.write("\t\t\t\t\t<p align=\"center\"><b>───── 냠냠 회원이 아니세요? ─────</b></p>\r\n");
      out.write("\t\t\t\t\t<p><input type=\"button\" name=\"join\" value=\"냠냠 계정 만들기\" onclick='location.href=\"joinPage.html\"'/></p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"bottom\">\r\n");
      out.write("\t\t\t<p align=\"center\">ⓒ2020 Nyam².com INC. or its affiliates.</p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</form>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
